# Generated by Django 3.2.9 on 2021-11-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название транспорта')),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='stock_multipler',
        ),
        migrations.AddField(
            model_name='sort',
            name='stock_multipler',
            field=models.FloatField(default=0, verbose_name='Процент скидки по акции'),
        ),
    ]
