# Generated by Django 3.2.9 on 2021-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название акции')),
                ('text', models.TextField(max_length=1200, verbose_name='Тект новости')),
                ('published', models.BooleanField(default=False, verbose_name='Статус публикации')),
                ('publication_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания новости')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
