# Generated by Django 3.2.9 on 2021-11-14 03:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20211114_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='default description', max_length=1200, verbose_name='Описание категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 3, 51, 44, 635233, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
